server:
  port: 8500
  servlet:
    context-path: /sso

spring:
  datasource:
    url: jdbc:mysql://10.0.2.23:3306/user_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123321
    driver-class-name: com.mysql.jdbc.Driver

