server:
  port: 80
  servlet:
    context-path: /user

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123321
    driver-class-name: com.mysql.jdbc.Driver
  security:
    oauth2:
      client:
        #不多说了
        client-id: web
        client-secret: 654321
        #Token获取地址
        access-token-uri: http://localhost:8500/sso/oauth/token
        #验证页面地址
        user-authorization-uri: http://localhost:8500/sso/oauth/authorize
      resource:
      #Token信息获取和校验地址
        token-info-uri: http://localhost:8500/sso/oauth/check_token
