security:
  oauth2:
   client:
     clientId: web
     clientSecret: 654321
     accessTokenUri: http://127.0.0.1:8500/sso/oauth/token
     userAuthorizationUri: http://127.0.0.1:8500/sso/oauth/authorize
     clientAuthenticationScheme: query
   resource:
     userInfoUri: http://127.0.0.1/user
   sso:
     login-path: /hello

server:
  port: 80
  servlet:
    context-path: /user